server:
  port: 8080
spring:
  freemarker:
    charset: UTF-8
    suffix=: .ftl
    content-type: text/html; charset=utf-8
    template-loader-path: classpath:/templates
    request-context-attribute: req
    cache: false
    enabled: true
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

springfox:
  documentation:
    enabled: true
    openapi-ui:
      enabled: true
      base-url: /doc